version: '3.1'
services:
  top.api:
    image: docker.pkg.github.com/Andrew1412Belous/nest-api/nest-api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:opt.app.env
